import { useMemo, useState } from "react";
import { RequestDetailDrawer } from "../components/RequestDetailDrawer";
import { EmptyState } from "../components/EmptyState";
import { formatTokens, useRequestList } from "../features/observability/useObservability";
import type { RequestListQuery, RequestStatus } from "../lib/desktop-api";

const statuses: Array<{ value: "" | RequestStatus; label: string }> = [{ value: "", label: "全部状态" }, { value: "succeeded", label: "成功" }, { value: "failed", label: "失败" }, { value: "cancelled", label: "已取消" }];
export function RequestListPage() {
  const [status, setStatus] = useState<"" | RequestStatus>(""); const [providerSlug, setProviderSlug] = useState(""); const [modelID, setModelID] = useState(""); const [cursor, setCursor] = useState<string | undefined>(); const [selectedID, setSelectedID] = useState<string | null>(null);
  const query = useMemo<RequestListQuery>(() => ({ page_size: 25, status: status || undefined, provider_slug: providerSlug.trim() || undefined, public_model_id: modelID.trim() || undefined, cursor }), [cursor, modelID, providerSlug, status]);
  const { data, loading, error, refresh } = useRequestList(query);
  const changeStatus = (value: "" | RequestStatus) => { setStatus(value); setCursor(undefined); };
  return <section className="page-section" aria-labelledby="requests-title"><div className="page-heading"><div><p className="eyebrow">请求记录</p><h1 id="requests-title">请求记录</h1><p>保留状态、路由快照和 Token；不保存请求正文。</p></div><button className="button button-secondary" type="button" onClick={() => void refresh()} disabled={loading}>刷新</button></div><div className="filter-bar"><label>状态<select className="text-input" value={status} onChange={(event) => changeStatus(event.target.value as "" | RequestStatus)}>{statuses.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>服务<input className="text-input" value={providerSlug} onChange={(event) => { setProviderSlug(event.target.value); setCursor(undefined); }} maxLength={128} placeholder="例如 openai" /></label><label>模型<input className="text-input" value={modelID} onChange={(event) => { setModelID(event.target.value); setCursor(undefined); }} maxLength={512} placeholder="例如 openai/gpt-4.1" /></label></div>{loading ? <p role="status">正在读取请求记录…</p> : error ? <section className="inline-error" role="alert"><p>{error}</p><button className="button button-secondary" type="button" onClick={() => void refresh()}>重试</button></section> : !data || data.data.length === 0 ? <EmptyState title="暂无匹配请求" description="调整筛选条件，或先通过本地网关发起一次请求。" /> : <><div className="data-panel table-scroll"><table><thead><tr><th>时间</th><th>服务 / 模型</th><th>状态</th><th>输出</th><th>耗时</th></tr></thead><tbody>{data.data.map((item) => <tr key={item.id}><td><button className="table-link" type="button" onClick={() => setSelectedID(item.id)}>{new Date(item.created_at).toLocaleString()}</button></td><td>{item.provider_slug} / {item.public_model_id}</td><td><span className={`status-chip status-${item.status}`}>{item.status}</span></td><td>{formatTokens(item.output_tokens)}</td><td>{item.duration_ms == null ? "—" : `${item.duration_ms} ms`}</td></tr>)}</tbody></table></div>{data.next_cursor ? <div className="pagination"><button className="button button-secondary" type="button" onClick={() => setCursor(data.next_cursor ?? undefined)}>下一页</button></div> : null}</>}<RequestDetailDrawer requestID={selectedID} onClose={() => setSelectedID(null)} /></section>;
}
