import { useMemo, useState } from "react";
import { EmptyState } from "../components/EmptyState";
import { UsageTable } from "./DashboardPage";
import { formatRate, formatTokens, recentUsageQuery, useUsage } from "../features/observability/useObservability";
export function UsagePage() {
  const [days, setDays] = useState<"7" | "30">("30"); const [providerSlug, setProviderSlug] = useState(""); const [modelID, setModelID] = useState("");
  const query = useMemo(() => { const base = recentUsageQuery(); const end = new Date(base.to_utc ?? Date.now()); return { provider_slug: providerSlug.trim() || undefined, public_model_id: modelID.trim() || undefined, from_utc: new Date(end.getTime() - (Number(days) - 1) * 86_400_000).toISOString(), to_utc: end.toISOString() }; }, [days, modelID, providerSlug]);
  const { data, loading, error, refresh } = useUsage(query);
  return <section className="page-section" aria-labelledby="usage-title"><div className="page-heading"><div><p className="eyebrow">用量</p><h1 id="usage-title">Token 用量</h1><p>按 UTC 日期汇总；未知 Token 与缓存命中率显示为 —。</p></div><button className="button button-secondary" type="button" onClick={() => void refresh()} disabled={loading}>刷新</button></div><div className="filter-bar"><label>时间范围<select className="text-input" value={days} onChange={(event) => setDays(event.target.value as "7" | "30")}><option value="7">最近 7 天</option><option value="30">最近 30 天</option></select></label><label>服务<input className="text-input" value={providerSlug} onChange={(event) => setProviderSlug(event.target.value)} maxLength={128} placeholder="例如 openai" /></label><label>模型<input className="text-input" value={modelID} onChange={(event) => setModelID(event.target.value)} maxLength={512} placeholder="例如 openai/gpt-4.1" /></label></div>{loading ? <p role="status">正在读取用量数据…</p> : error ? <section className="inline-error" role="alert"><p>{error}</p><button className="button button-secondary" type="button" onClick={() => void refresh()}>重试</button></section> : !data || data.summary.request_count === 0 ? <EmptyState title="暂无用量数据" description="请求完成并报告 Token 后，会在这里形成日汇总。" /> : <><div className="metric-grid"><Metric label="输入 Token" value={formatTokens(data.summary.input_tokens)} /><Metric label="输出 Token" value={formatTokens(data.summary.output_tokens)} /><Metric label="缓存 Token" value={formatTokens(data.summary.cached_input_tokens)} /><Metric label="缓存命中率" value={formatRate(data.summary.cache_hit_rate_basis_points)} /></div><UsageTable points={data.series.data} /></>}</section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>; }
